services:
    _defaults:
        autowire: true
        autoconfigure: true

    Answear\MessengerHeartbeatBundle\Transport\TransportFactory:
        decorates: 'messenger.transport.amqp.factory'
        tags:
            - {name: 'messenger.transport_factory', priority: 100}

    Answear\MessengerHeartbeatBundle\EventSubscriber\SendFailedMessageToFailureTransportListener:
        decorates: 'messenger.failure.send_failed_message_to_failure_transport_listener'
        arguments: ['@.inner']
