services:
    _defaults:
        autowire: true
        autoconfigure: true


    Answear\MessengerHeartbeatBundle\EventSubscriber\HeartbeatEventsSubscriber:
        arguments:
            $receiverLocator: '@messenger.receiver_locator'

    Answear\MessengerHeartbeatBundle\Service\SignalHandler: ~

    Answear\MessengerHeartbeatBundle\EventSubscriber\SendFailedMessageToFailureTransportListener:
        decorates: 'messenger.failure.send_failed_message_to_failure_transport_listener'
        arguments: ['@.inner']

    Answear\MessengerHeartbeatBundle\EventSubscriber\SendFailedMessageForRetryListener:
        decorates: 'messenger.retry.send_failed_message_for_retry_listener'
        arguments: ['@.inner']
