name: "Continuous Integration"

on:
    pull_request: null

jobs:
    phpunit:
        name: "PHPUnit"
        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.1"
                    - "8.2"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
              with:
                  fetch-depth: 2

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"

            - name: "Cache dependencies installed with composer"
              uses: "actions/cache@v2"
              with:
                  path: "~/.composer/cache"
                  key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
                  restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

            - name: "Update dependencies with composer"
              run: "composer update --no-interaction --no-progress --no-suggest"

            - name: "Run PHPUnit"
              run: "vendor/bin/phpunit"
